name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 19, 20]
        stability: [prefer-lowest, prefer-stable]
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }} (${{ matrix.stability }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Setup ganache
        run: npm install -g ganache-cli
      - name: Start ganache
        run: ganache-cli --gasLimit 0xfffffffffff -e 1000000 -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" > /dev/null &
      - name: Setup truffle
        run: npm install -g truffle
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
            NODE_OPTIONS: --experimental-vm-modules
